services:
  mysql:
    image: mysql:8.0
    ports:
      - '3307:3306'
    environment:
      - MYSQL_DATABASE=db_example
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=springuser
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
